api_dieta_item:
    resource: "@DietaBundle/Controller/DietaItemController.php"
    type:     annotation

api_user:
    resource: "@DietaBundle/Controller/UserController.php"
    type:     annotation

api_receta:
    resource: "@DietaBundle/Controller/RecetaController.php"
    type:     annotation

api_dieta:
    resource: "@DietaBundle/Controller/DietaController.php"
    type:     annotation

#FOS routing
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }







