dieta_dieta_item:
    resource: "@DietaBundle/Controller/DietaItemController.php"
    type:     annotation

api_user:
    resource: "@DietaBundle/Controller/UserController.php"
    type:     annotation

api_dieta:
    resource: "@DietaBundle/Controller/RecetaController.php"
    type:     annotation






