# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend:
            pattern: ^/
            security: false
        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        login:
            pattern: ^/login
            anonymous: true
            form_login:
                  # The route name that the login form submits to
                  check_path:               /login_check
                  success_handler:          lexik_jwt_authentication.handler.authentication_success
                  failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                  require_previous_session: false

            #logout:
                  # The route name the user can go to in order to logout
             #     path: security_logout

        main:
            pattern:   ^/api
            stateless: true
            guard:
                  authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
            - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
            - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    #  - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #
    # allow anonymous API - if auth is needed, it's handled in the controller
    #  - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #