<?php

namespace DietaBundle\Repository;

/**
 * DietaItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietaItemRepository extends \Doctrine\ORM\EntityRepository
{
}
