<?php

namespace DietaBundle\Repository;

/**
 * DietaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietaRepository extends \Doctrine\ORM\EntityRepository
{
}
